version: 2
updates:
  # maintain npm dependancies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # maintain github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"