name: Publish to npm

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    # get latest major versions from node
    get-lts-versions:
        runs-on: ubuntu-latest
        outputs:
            versions: ${{ steps.get-versions.outputs.lts }}
        steps:
            - id: get-versions
              uses: msimerson/node-lts-versions@v2

    # run test
    test:
        needs: get-lts-versions
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ${{ fromJson(needs.get-lts-versions.outputs.versions) }}
            fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

            - name: Run Prettier
              run: npx prettier --check .

            - name: Build ESM version
              run: npm run build

            - name: Run Tests
              run: npm test

    # publish to npm
    publish-npm:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm ci

            - name: Build ESM and JSDoc Types
              run: |
                  npm run build
                  npm run build:types

            - name: Publish Package via Trusted Publisher
              run: npm publish --access public --provenance
